### ISSUE TITLE
Return `ControlFlow` from AST visitor methods

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/solar#14]
Currently AST visitors do not return anything, whereas it would be beneficial to return a `ControlFlow` value, with the associated break type defined by implementors. By default, all functions should always return `Continue(())`, and implementors may choose to break early.

https://github.com/paradigmxyz/sulk/blob/5f827dd5a0fed12f8e57c48ac60e371b98d921a3/crates/ast/src/visit.rs#L7-L10

**Comment by mahmudsudo** [comment]
Hi can I take on this ?
