### ISSUE TITLE
Print AST statistics

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/solar#25]
### Describe the feature

Add a `-Z ast-stats` flag that prints the size of the AST and of each node for each input file to stderr.

### Additional context

See rustc:
- implementation: <https://github.com/rust-lang/rust/blob/8a8ad3433e4168f54ac1364f85da694be9eeca7c/compiler/rustc_passes/src/hir_stats.rs#L81-L88>
- output file: <https://github.com/rust-lang/rust/blob/8a8ad3433e4168f54ac1364f85da694be9eeca7c/tests/ui/stats/hir-stats.stderr>

**Comment by adpthegreat** [comment]
Hi @DaniPopes please can you assign this to me? Thanks!
